apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: loantrack
spec:
  type: NodePort   # NodePort for easy localhost access
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080   # you can change this if the port is taken
